### ISSUE TITLE
Cocoapod?

### ISSUE THREAD

**Issue by jhurliman** [iluuu1994/ITSwitch#23]
A podspec and publishing to the Cocoapods repo for this project would be great.

**Comment by iluuu1994** [comment]
It sure would. Let me see tonight if I find the time.

**Comment by iiiyu** [comment]
I also want to pod support.

**Comment by iluuu1994** [comment]
@iiiyu Currently, I don't really have the time or energy to do this, especially since I've never really used cocoapod. Of course, you can do so yourself and submit a pull-request, which I will gladly accept.

**Comment by iiiyu** [comment]
@jhurliman @iluuu1994  

Updating spec repo `master`
  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/364154821c2dc51eb5663fdc88d834e296c4de11/Specs/ITSwitch/1.0/ITSwitch.podspec.json

I have already submitted Podspec to Trunk
enjoy!!!
