### ISSUE TITLE
Weak reference error during compile

### ISSUE THREAD

**Issue by epsilontik** [iluuu1994/ITSwitch#31]
Hi there,
Most likely this is not a bug in your project but rather a typical "misuse" scenario :-)

I'm trying to include this wonderful button into one of my Xcode projects (I'm using Objective C under Xcode 6.4). However, as soon as I add the files to my project I constantly get a compile error:

ITSwitch.m:44:5: The current deployment target does not support automated __weak references
About the marked  line below 
@interface ITSwitch () {
 ------->>>>   __weak id _target;
    SEL _action;
}

I already tried to change the settings for deployment but I cannot find anything that would solve this error. The compile settings require the latest OSX SDK (10.10) and are pretty much standard. 

Did you encounter such an error during development and do you have an idea where I should look at?

Thanks

**Comment by iluuu1994** [comment]
Well, what is your deploy target? Weak references are available since 10.7 AFAIK.

**Comment by epsilontik** [comment]
Man, I'm so stupid. I changed the reference SDK the whole time rather than the target one. Now it's working. Thanks for opening up my eyes.

**Comment by iluuu1994** [comment]
No worries man, you're welcome.
