### ISSUE TITLE
Clips subviews

### ISSUE THREAD

**Issue by billburgess** [iluuu1994/ITSwitch#33]
During the on/off animation the switch extends outside the bounds of the border causing a noticeable flat spot on either side of the switch. It seems like the switch should clip under the border for the switch so that it doesn't cause this flat feeling when it bounces outside the view. I looked at the iOS UISwitch and the animation they use is less pronounced and doesn't actually extend all the way to the edge of the control, avoiding the flat look. Maybe this could be achieved by tightening up the bounce distance so it can't ever get to the edge. Thanks!

**Comment by iluuu1994** [comment]
Have you embedded the switch in a larger layer-backed view? That should fix the issue. This is not happening in the demo, right?

**Comment by billburgess** [comment]
I couldn't get the demo to run on El Capitan. I did however enable the CA Layer for my view in IB and that fixed the issue. Thanks!
