### ISSUE TITLE
on/off labels

### ISSUE THREAD

**Issue by SchwiftyLife** [iluuu1994/ITSwitch#37]
hi
its nice to have on/off labels in the ITSwitch . like this picture:
<img width="757" alt="3e" src="https://cloud.githubusercontent.com/assets/16489849/17861663/371084dc-68a7-11e6-9534-0c969242b862.png">

**Comment by iluuu1994** [comment]
Probably not gonna happen. This switch was developed as a part of a project that I'm no longer working on. Thus I have no time/reason to extend it. If you do I'll gladly accept a pull-request though. 👍

**Comment by zizigolllo** [comment]
oh okay , thanks for the response though.

ps. i dont have the experience to do it in obj. c , maybe if it was in swift i could try though :b , do you know any similar project thats written in swift?

**Comment by iluuu1994** [comment]
I don't think there is a production-ready one in Swift. The code should be understandable though even if you don't write lots of Objective-C.

**Comment by zizigolllo** [comment]
obj-c is like Chinese to my eyes :b i just use ready classes  in my swift projects. :(
i found some switches like yours but they are for iOS , i hope i can tweak them so i can use them for macOS.

**Comment by OskarGroth** [comment]
Thanks Ilija for this project. I've created a Swift version of ITSwitch with a bunch of styling options such as knob images:
https://github.com/OskarGroth/OGSwitch

I don't really think switch On/Off labels are necessary, but if you need it, it should be trivial for you to add. Don't forget to send a PR :)

**Comment by iluuu1994** [comment]
I'm closing this as `OGSwitch` offers a solution to this 🙂
