### ISSUE TITLE
10.13 Shadow issues - and fix.

### ISSUE THREAD

**Issue by curthard89** [iluuu1994/ITSwitch#38]
Just a quick note,

On 10.13, the shadows are cut off even if the superview is layer backed.

From the release notes on this:

> Stricter allocation of view-backing layers
> 
> macOS 10.13 is stricter in some cases about when it allocates view-backing layers for certain views. As before, if your view relies on having a layer (e.g. for the purpose of setting layer properties), it should receive [view wantsLayer:YES] and should probably also return YES from -wantsUpdateLayer.
> 
> Ownership of view-backing layer properties
> 
> macOS 10.13 is more consistent around updates to properties of views' layers (that is, layers that are the .layer of some NSView, however created). As before, if an application modifies such a layer by changing any of the following properties, the behavior of the application is undefined: bounds, position, zPosition, anchorPoint, anchorPointZ, transform, affineTransform, frame, hidden, geometryFlipped, masksToBounds, opaque, compositingFilter, filters, shadowColor, shadowOpacity, shadowOffset, shadowRadius, shadowPath.
> 
> As before, for best results, a view that modifies any other properties of its layer should also faithfully implement drawRect: to reflect such modifications, since not all layer properties can be automatically represented in all drawing circumstances. For instance, if a view's -updateLayer implementation changes the border properties of its layer, its -drawRect: should draw an equivalent border.

Basically you need to explicitly set the control's masksToBounds to be NO and it will work again :-).

Just a heads up.

**Comment by iluuu1994** [comment]
@curthard89 Do you have a working solution? I'm not actively doing MacOS development anymore. I'd really appreciate a pull request 😅

**Comment by curthard89** [comment]
In my last comment ;-), setting _rootLater.masksToBounds = NO; seems to do the trick, i don't understand why they changed this, but hey ho! When i have a moment i can do a pull request :).

**Comment by iluuu1994** [comment]
@curthard89 Great! I appreciate it!

**Comment by curthard89** [comment]
No worries, we use it in IconJar, well, a heavily modded version of it but still, don't worry, your in the acknowledgments :), thanks for the good work :).

**Comment by iluuu1994** [comment]
That's awesome! I forget that people actually use my open source code 😄

**Comment by iluuu1994** [comment]
Finally got around fixing this issue. Also created a new demo project that actually works. Thanks again 🙂
